#!/bin/sh
export TIME_TENSORS_RUN="multi"
unset OMP_NUM_THREADS
unset OPENBLAS_NUM_THREADS
unset MKL_NUM_THREADS
unset VECLIB_MAXIMUM_THREADS
unset NUMEXPR_NUM_THREADS
unset NUM_INTER_THREADS
unset NUM_INTRA_THREADS
unset XLA_FLAGS
